spring.application.name=transaction-anomaly-backend

# =========================================================
# DATABASE
# =========================================================

spring.datasource.url=jdbc:mysql://localhost:3306/transaction_anomaly
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Anushka@5905}

# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# =========================================================
# JWT
# =========================================================

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600000}

# =========================================================
# EMAIL / SMTP
# =========================================================

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

alert.email.to=${ALERT_EMAIL_TO:}

# =========================================================
# ERROR RESPONSE
# =========================================================

server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never